---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: grafana-admin-password-secret
    creationPolicy: Owner
  data:
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: 3d80e297-7beb-48c9-adea-1a0f88ecc8ac # vaultwarden: homelab-talos/grafana
        property: password
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: grafana-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      remoteRef:
        key: 1b036df2-be8f-4b3a-bd6d-38eb1faed5d8 # vaultwarden: homelab-talos/grafana-oidc
        property: username
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
      remoteRef:
        key: 1b036df2-be8f-4b3a-bd6d-38eb1faed5d8 # vaultwarden: homelab-talos/grafana-oidc
        property: password
