---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: grafana-admin-password-secret
    creationPolicy: Owner
  data:
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: 3d80e297-7beb-48c9-adea-1a0f88ecc8ac # vaultwarden: homelab-talos/grafana
        property: password
