apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-cli
type: Opaque
stringData:
  BW_HOST: ENC[AES256_GCM,data:UoNOpO2hHqZA+YJo0FlDlbZzJ/s5ZHs=,iv:hYj2YLCq8ut2SjjioAZi83FSyisn/B0tOK8WV9AM6/0=,tag:PNtKRRBp4g0s4rhasRFs1Q==,type:str]
  BW_CLIENTID: ENC[AES256_GCM,data:3rqrV7XzenjMiKYO3uGM824WgxXmB0DT3YNjIz8YVPdnzoCU0QPO60Y=,iv:RDzvw5GMJWPTntdpdUBHpfKnoyGuye0Nkk/V3YJFHV0=,tag:nnto+pJ2ZIFo5Pl9QSg6tA==,type:str]
  BW_CLIENTSECRET: ENC[AES256_GCM,data:p+9EdGWDx3suzdd10vNd77eIlaO25REwfpX99VSj,iv:e6qJxxgUVExA8YfBHrTRlFLQz+zBiqwjqX+h5RB5R08=,tag:Uqqeyb+TfNA+Mym3l7rnAw==,type:str]
  BW_USER: ENC[AES256_GCM,data:IN1FuGkdAMYyRMtwrpRvZXTd+vhmdH1i,iv:U3j7/ME8k84gCXIMzyDyse+qq4NUB7TEWQLrECcnno4=,tag:gGzMOH5BhdHS+Lj48hJB0A==,type:str]
  BW_PASSWORD: ENC[AES256_GCM,data:DH0LPP7DBKLGfRk2BIPStSh4,iv:Cnwq8jMtdlroNv3k75MPz+3cjDkZQM2nOUJUb/qXD7Y=,tag:awKckvBATCjKn12tqUuyGg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWFo0U0lKNkk4Q1p2eUM0
        Y1RlR01FZ1hwWERMUkV6clhVK1ZPOHQ4bVZRCkVlNXpqWmVMZXVrdTFqZmVzckRC
        YUxvbnczbkxuYXEwOVF6S0hWV1RPbG8KLS0tIGNDRW4wYnJvSW9lVVVuVlh4aUVM
        bjRkRnJzNVkyMERqazJ2RGU4VGR4ODQKO+rilP1wrizH6MLV8Nsb4ufA9tz2mR2u
        sYlN+dSulmngwwV67OamHi+VRxF6C3hgPJtwW8aNSxTPEsN16YqGsA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ezazx7ck5002pq8qkla2lytrrtfq5hqn9xlwl7wc0ea43qjdle4sllf2g9
  encrypted_regex: ^(data|stringData|driver)$
  lastmodified: "2026-07-04T22:11:54Z"
  mac: ENC[AES256_GCM,data:PWRWGTl3hdEBtLlTLZL9X99Z/T64XlJGNPxAjaiWLDNX0xObogjttSW0v0X7vYF/0HRL0uk0p6IfxA+bjQlPUWbOQ6YPj7SQdfNPomUE1I4b9k/Tn1jld4IcX5joC4fJPKo8CzQp2qQdP7R1M3cILhvznC5+W/mOYE9W7DqW2bA=,iv:xIQPG0C8911TJzFLC/0nh4zMgsQOZ2/TtSnx7mF4qNg=,tag:U8MJ0s8x6/53FoOSbiLoYw==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
