---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-iscsi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: truenas-iscsi-secret-config
    creationPolicy: Owner
    template:
      data:
        driver-config-file.yaml: "{{ .config }}"
  data:
    - secretKey: config
      remoteRef:
        key: 5d1bf64b-2a41-4b8f-92ec-67d526304ccc # vaultwarden: homelab-talos/truenas-iscsi (notes = driver yaml)
