---
area/bootstrap:
  - changed-files:
      - any-glob-to-any-file:
          - bootstrap/**/*
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - CLAUDE.md
          - docs/**/*
area/github:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**/*
area/kubernetes:
  - changed-files:
      - any-glob-to-any-file:
          - kubernetes/**/*
area/renovate:
  - changed-files:
      - any-glob-to-any-file:
          - .renovaterc.json5
area/taskfile:
  - changed-files:
      - any-glob-to-any-file:
          - Taskfile.yaml
