---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: cloudflare-dns-secret # name the HelmRelease already references
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: 3411038f-cfb2-49ba-b998-144bcb54deec # vaultwarden: homelab-talos/cloudflare-dns
        property: api-token
