---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kibana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: kibana-es-credentials
    creationPolicy: Owner
  data:
    - secretKey: ELASTICSEARCH_PASSWORD
      remoteRef:
        key: REPLACE-WITH-UUID # vaultwarden: homelab-talos/kibana (login, user kibana_system)
        property: password
