---
apiVersion: v1
kind: Service
metadata:
  name: litellm
  labels:
    app: litellm # ServiceMonitor selects on this
spec:
  selector:
    app: litellm
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
