---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: github-webhook-token-secret # name the Receiver references
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: 08ace1aa-20f9-4984-8bca-52b5c840f276 # vaultwarden: homelab-talos/flux-github-webhook (field: token)
        property: token
