---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: bgp
spec:
  # routed prefix outside the node subnet; opt-in via Service label announce=bgp
  allowFirstLastIPs: "No"
  blocks:
    - cidr: "10.1.81.0/24"
  serviceSelector:
    matchLabels:
      announce: bgp
