---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-index-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-fields
  target:
    name: es-index-manager
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: 161a1023-a667-4cdb-bd1c-b8b72d337a60 # vaultwarden: homelab-talos/es-index-manager (field: api-key = "encoded" from _security/api_key)
        property: api-key
