---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-nfs
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-notes
  target:
    name: truenas-nfs-secret-config
    creationPolicy: Owner
    template:
      data:
        driver-config-file.yaml: "{{ .config }}"
  data:
    - secretKey: config
      remoteRef:
        key: 374d6a1a-4b44-4b73-aa62-6f134bd1e87d # vaultwarden: homelab-talos/truenas-nfs (notes = driver yaml)
