---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./rbac.yaml
  - ./ocirepository.yaml
  - ./httproute.yaml
  - ./networkpolicy.yaml
