---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./projectconfig.yaml
  - ./externalsecret.yaml
  - ./analysistemplate.yaml
  - ./warehouse.yaml
  - ./stage-staging.yaml
  - ./stage-production.yaml
