---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # per-gateway config
  - ./external
  - ./internal
  # shared by both gateways
  - ./gatewayclass.yaml
  - ./envoy.yaml # GatewayClass default EnvoyProxy — internal inherits it
  - ./httpredirect.yaml
