---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fluent-bit
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: fluent-bit-es-credentials
    creationPolicy: Owner
  data:
    - secretKey: ES_USER
      remoteRef:
        key: f2ef876e-bf21-4489-9805-ab3c8f4f9e3b # vaultwarden: homelab-talos/fluent-bit (login)
        property: username
    - secretKey: ES_PASSWORD
      remoteRef:
        key: f2ef876e-bf21-4489-9805-ab3c8f4f9e3b # same item
        property: password
